#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;

$app = require __DIR__.'/bootstrap/start.php';

/*
 * Set up the console application.
 */
$app->instance('console', $console = new Application());
$app->register('FluxBB\Installer\Console\ConsoleServiceProvider');

$app->boot();

/*
 * Run and exit with the response status code.
 */
$status = $console->run();

exit($status);
